### ISSUE TITLE
Many plugins have prompted such a mistake and failed to load

### ISSUE THREAD

**Issue by mainwindow** [DragonetMC/GlowstonePlusPlus#1]
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_8_R3/CraftServer
        at net.citizensnpcs.util.Util.getMinecraftRevision(Util.java:78)
        at net.citizensnpcs.Citizens.onEnable(Citizens.java:262)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
        at org.dragonet.plugin.MixedPluginManager.enablePlugin(MixedPluginManager.java:471)
        at net.glowstone.GlowServer.enablePlugins(GlowServer.java:818)
        at net.glowstone.GlowServer.start(GlowServer.java:517)
        at net.glowstone.GlowServer.main(GlowServer.java:121)
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_8_R3.CraftServer
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)

What should I do...

**Comment by RandomAltThingy** [comment]
You cannot use plugins that import the net.minecraft class or org.bukkit.craftbukkit, due to the craftbukkit source being taken down in the DMCA takedown

**Comment by RandomAltThingy** [comment]
And this is not the repo. This is the dragonet version of glowstoneplusplus. Please report on the @GlowStonePlusPlus repo
