### ISSUE TITLE
Can not save OP information

### ISSUE THREAD

**Issue by mainwindow** [DragonetMC/GlowstonePlusPlus#2]
Error reading from: config\ops.json
 java.lang.NullPointerException
 at net.glowstone.util.bans.JsonListFile.load(JsonListFile.java:52)
 at net.glowstone.GlowServer.start(GlowServer.java:464)
 at net.glowstone.GlowServer.main(GlowServer.java:121)

What...:(...
I use Dragonet.

**Comment by RandomAltThingy** [comment]
Read previous comment
